include: package:flutter_lints/flutter.yaml

# Additional lint rules can be added here
linter:
  rules:
    # Add custom rules if needed
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_print: true
